frameworkVersion: '>=1.79.0'

service:
  name: Colin30ServicesCatcher

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  httpApi:
    payload: '2.0'

functions:
  catcher:
    handler: handler.catcher
    events:
      - httpApi: '*'
