AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 100

Resources:
  KeywordMultiplierApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        Base:
          Type: Api
          Properties:
            Path: /
            Method: any
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any