service:
  name: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${env:REGION}
  stackName: ${env:SERVICE_NAME}Stack
  endpointType: regional
  role: ${env:ACCESS_ROLE}
  httpApi:
    name: ${env:GATEWAY_NAME}
    payload: '2.0'
    cors:
      allowedOrigins:
        - ${env:LOCAL_ORIGIN}
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
      allowCredentials: true
      maxAge: 6000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:${env:REGION}:*:table/${env:TABLE_NAME}

functions:
  createTrialHandler:
    name: ${env:SERVICE_NAME}-createTrialHandler
    handler: index.createTrialHandler
    events:
      - httpApi:
          path: /${env:RESOURCE_NAME}
          method: POST
  getMetaHandler:
    name: ${env:SERVICE_NAME}-getMetaHandler
    handler: index.getMetaHandler
    events:
      - httpApi:
          path: /ke
          method: GET
  getVolumesHandler:
    name: ${env:SERVICE_NAME}-getVolumesHandler
    handler: index.getVolumesHandler
    events:
      - httpApi:
          path: /ke
          method: POST
  preOrderHandler:
    name: ${env:SERVICE_NAME}-preOrderHandler
    handler: index.preOrderHandler
    events:
      - httpApi:
          path: /ke/pre-order
          method: POST
  lowCreditsAlertHandler:
    name: ${env:SERVICE_NAME}-lowCreditsAlertHandler
    handler: index.lowCreditsAlertHandler
    events:
      - httpApi:
          path: /ke/low-credits
          method: POST
      - sns:
          arn: ${env:SNS_ARN}

configValidationMode: warn

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${env:NODE_ENV}
  domains:
    production: ${env:DOMAIN}
    staging: sta-${env:DOMAIN}
    development: dev-${env:DOMAIN}
  dotenv:
    logging: false
  serverless-offline:
    httpPort: ${env:LOCAL_SLS_PORT}
    noPrependStageInUrl: true
    resourceRoutes: true
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true
  customDomain:
    stage: ${self:custom.stage}
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: ${env:API_BASE_PATH}
    endpointType: regional
    apiType: http
    autoDomain: true

resources:
  Resources:
    kmTrials:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1

