service:
  name: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  httpApi:
    payload: '2.0'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  dotenv:
    logging: false
  serverless-offline:
    httpPort: ${env:LOCAL_PORT}
    noPrependStageInUrl: true
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules: true
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: ${env:STAGE}
    endpointType: regional
    apiType: http
    autoDomain: true

package:
  individually: true

functions:
  catcher:
    handler: handler.catcher
    stage: ${env:STAGE}
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /{path+}
          method: GET