service:
  name: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}
  httpApi:
    payload: '2.0'

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    logging: false
    # path: default
    # basePath: default
    # include: default
    # exclude: default


functions:
  catcher:
    handler: handler.catcher
    events:
      - httpApi:
          method: GET
          path: '*'