service:
  name: ${env:SLS_SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${env:REGION}
  stackName: ${env:SLS_SERVICE_NAME}-stack
  endpointType: regional
  role: ${env:ACCESS_ROLE}
  httpApi:
    name: ${env:SLS_SERVICE_NAME}-httpapi
    payload: '2.0'
    cors:
      allowedOrigins:
        - ${env:CORS_LIVE_ORIGIN}
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: true
      maxAge: 6000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:${env:REGION}:*:table/${env:TABLE_NAME}

functions:
  contactHandler:
    name: ${env:SLS_SERVICE_NAME}-contactHandler
    handler: v1/index.contactHandler
    events:
      - httpApi:
          path: /contact
          method: POST

configValidationMode: warn

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${env:NODE_ENV}
  domains:
    production: ${env:BASE_DOMAIN}
    staging: sta-${env:BASE_DOMAIN}
    development: dev-${env:BASE_DOMAIN}
  dotenv:
    logging: false
  serverless-offline:
    httpPort: ${env:SLS_OFFLINE_PORT}
    noPrependStageInUrl: true
    resourceRoutes: false
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true
  customDomain:
    stage: ${self:custom.stage}
    domainName: ${self:custom.domains.${self:custom.stage}}
    endpointType: regional
    apiType: http
    autoDomain: true

resources:
  Resources:
    NcaContent:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: app
            AttributeType: S
        KeySchema:
          - AttributeName: app
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
