service:
  name: ${env:SLS_SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${env:REGION}
  stackName: ${env:SLS_SERVICE_NAME}Stack
  endpointType: regional
  role: ${env:ACCESS_ROLE}
  httpApi:
    name: ${env:HTTPAPI_NAME}
    payload: '2.0'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3.ListObjects
        - s3:GetObject
      Resource:
        - arn:aws:s3:${env:CDN_BUCKET_NAME}

functions:
  rootHandler:
    name: ${env:SLS_SERVICE_NAME}-rootHandler
    handler: v1/handlers.rootHandler
    events:
      - httpApi:
          path: /{proxy+}
          method: GET
  appsHandler:
    name: ${env:SLS_SERVICE_NAME}-appsHandler
    handler: v1/handlers.appsHandler
    events:
      - httpApi:
          path: /apps/{proxy+}
          method: GET

configValidationMode: warn

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  stage: ${env:NODE_ENV}
  domains:
    production: ${env:BASE_DOMAIN}
    staging: sta-${env:BASE_DOMAIN}
    development: dev-${env:BASE_DOMAIN}
  dotenv:
    logging: false
  serverless-offline:
    httpPort: ${env:SLS_OFFLINE_PORT}
    noPrependStageInUrl: false
    resourceRoutes: false
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${env:NODE_ENV}
    endpointType: regional
    apiType: http
    autoDomain: true