service:
  name: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  stackName: ${env:SERVICE_NAME}
  endpointType: regional
  httpApi:
    name: ${env:GATEWAY_NAME}
    payload: '2.0'

functions:
  getAll:
    name: ${env:SERVICE_NAME}
    handler: index.getAll
    stage: ${env:STAGE}
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /{proxy+}
          method: GET

configValidationMode: warn

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  dotenv:
    logging: false
  serverless-offline:
    httpPort: ${env:LOCAL_PORT}
    noPrependStageInUrl: true
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules: true
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: ${env:STAGE}
    endpointType: regional
    apiType: http
    autoDomain: true

package:
  individually: true