service:
  name: ${env:SLS_SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${env:REGION}
  stackName: ${env:SLS_SERVICE_NAME}
  role: ${env:ACCESS_ROLE}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3.ListObjects
      - s3:GetObject
      - s3:PutObject
      - kms:Decrypt
    Resource:
      - arn:aws:s3:${env:PRERENDERS_BUCKET}

functions:
  viewerRequest:
    name: ${env:SLS_SERVICE_NAME}-viewerRequest
    handler: v1/handlers.viewerRequest
    memorySize: 128
    timeout: 5
  originRequest:
    name: ${env:SLS_SERVICE_NAME}-originRequest
    handler: v1/handlers.originRequest
    memorySize: 3008
    timeout: 30

configValidationMode: warn

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  stage: ${env:NODE_ENV}
  dotenv:
    logging: false
  webpack:
    webpackConfig: webpackConfig.js
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
    keepOutputDirectory: true