AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 100
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.main
      Runtime: nodejs12.x
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY